language: cpp

compiler:
        - gcc

before_install:
        - sudo add-apt-repository -y ppa:andykimpe/cmake
        - sudo apt-get -qq update

install:
        - sudo apt-get install cmake 
        - if [ "$CXX" == "g++"     ]; then .travis_scripts/gcc.sh; fi

script: 
        - mkdir build; pushd build;
        - cmake -D CMAKE_CXX_FLAGS=--coverage .. && make debug
        - make run_test
        - popd;

after_success:
        - .travis_scripts/coveralls.sh
